criaCartao("Células", "O que é a mitose?", "A mitose é o processo de divisão celular que resulta em duas células-filhas idênticas à célula original.");
criaCartao("Genética", "O que é o DNA?", "O DNA (ácido desoxirribonucleico) é a molécula que contém a informação genética responsável pelo funcionamento dos organismos.");
criaCartao("Evolução", "O que é a teoria da seleção natural?", "A seleção natural é o processo pelo qual organismos mais bem adaptados ao ambiente têm maior chance de sobreviver e reproduzir.");
criaCartao("Fisiologia", "O que é homeostase?", "Homeostase é o processo pelo qual os organismos mantêm o equilíbrio interno, como temperatura e pH, dentro de limites ideais.");
criaCartao("Anatomia", "Qual a principal função do sistema circulatório?", "O sistema circulatório transporta oxigênio, nutrientes e resíduos através do corpo.");
criaCartao("Ecologia", "O que é uma cadeia alimentar?", "Uma cadeia alimentar é uma sequência de organismos onde cada um serve de alimento para o próximo, transferindo energia e nutrientes.");
criaCartao("Botânica", "O que são cloroplastos?", "Cloroplastos são organelas celulares responsáveis pela fotossíntese nas células vegetais.");
criaCartao("Microbiologia", "O que são bactérias?", "Bactérias são organismos unicelulares procariontes, encontrados em diversos ambientes.");
criaCartao("Biotecnologia", "O que é engenharia genética?", "Engenharia genética é o processo de modificar geneticamente organismos para obter características desejadas.");
criaCartao("Imunologia", "O que são anticorpos?", "Anticorpos são proteínas produzidas pelo sistema imunológico para identificar e neutralizar patógenos.");
criaCartao("Células", "O que é o núcleo celular?", "O núcleo celular é a organela que contém o material genético (DNA) e controla as funções celulares.");
criaCartao("Fisiologia", "Qual a função dos rins?", "Os rins filtram o sangue, removem resíduos e excesso de água, formando a urina.");
criaCartao("Biologia Molecular", "O que é a transcrição?", "A transcrição é o processo pelo qual uma cópia do DNA é feita em RNA mensageiro, que será usado para produzir proteínas.");
criaCartao("Zoologia", "O que são vertebrados?", "Vertebrados são animais que possuem coluna vertebral ou espinha dorsal.");
criaCartao("Botânica", "O que é a fotossíntese?", "A fotossíntese é o processo pelo qual as plantas convertem luz solar em energia, produzindo glicose e oxigênio.");
criaCartao("Evolução", "O que são mutações?", "Mutações são alterações no material genético que podem ser causadas por fatores internos ou externos.");
criaCartao("Ecologia", "O que é a biodiversidade?", "A biodiversidade é a variedade de formas de vida no planeta, incluindo diversidade genética, de espécies e de ecossistemas.");
criaCartao("Fisiologia", "O que é a respiração celular?", "A respiração celular é o processo pelo qual as células geram energia através da quebra de glicose com a ajuda de oxigênio.");
criaCartao("Neurobiologia", "O que são neurotransmissores?", "Neurotransmissores são substâncias químicas que transmitem sinais entre os neurônios.");
criaCartao("Células", "O que são mitocôndrias?", "Mitocôndrias são organelas responsáveis pela produção de energia nas células através da respiração celular.");
criaCartao("Genética", "O que é o cromossomo?", "Cromossomos são estruturas formadas por DNA e proteínas que contêm a informação genética de um organismo.");
criaCartao("Ecologia", "O que é uma população?", "População é o conjunto de organismos da mesma espécie que vivem em uma determinada área geográfica.");
criaCartao("Fisiologia", "Qual a função do sistema digestivo?", "O sistema digestivo quebra os alimentos e absorve os nutrientes necessários para o corpo.");
criaCartao("Botânica", "O que são raízes?", "As raízes são órgãos das plantas responsáveis pela fixação no solo e pela absorção de água e nutrientes.");
criaCartao("Imunologia", "O que é o sistema imunológico?", "O sistema imunológico defende o corpo contra infecções e doenças causadas por microorganismos patogênicos.");
criaCartao("Zoologia", "O que são invertebrados?", "Invertebrados são animais que não possuem coluna vertebral.");
criaCartao("Genética", "O que é o gene?", "Gene é a unidade básica de hereditariedade, composta por sequências de DNA que codificam proteínas ou características.");
criaCartao("Fisiologia", "O que é o sistema nervoso?", "O sistema nervoso controla e coordena as funções do corpo, transmitindo sinais entre o cérebro e outras partes do corpo.");
criaCartao("Biologia Molecular", "O que é a tradução?", "Tradução é o processo pelo qual o RNA mensageiro é usado para produzir uma proteína na célula.");
criaCartao("Ecologia", "O que são os decompositores?", "Decompositores são organismos, como fungos e bactérias, que quebram matéria orgânica, reciclando nutrientes no ecossistema.");
criaCartao("Fisiologia", "O que são hormônios?", "Hormônios são substâncias químicas produzidas por glândulas que regulam diversas funções no corpo.");
criaCartao("Botânica", "O que é a polinização?", "A polinização é o processo de transferência de pólen das anteras para o estigma das flores, essencial para a reprodução das plantas.");
criaCartao("Zoologia", "O que são mamíferos?", "Mamíferos são animais vertebrados que possuem pelos, glândulas mamárias e dão à luz filhotes, com exceção dos monotremados.");
criaCartao("Imunologia", "O que é uma vacina?", "Uma vacina é uma substância que estimula o sistema imunológico a produzir anticorpos contra um patógeno específico.");
criaCartao("Genética", "O que é o fenótipo?", "Fenótipo é a expressão das características físicas de um organismo, resultado da interação entre o genótipo e o ambiente.");
criaCartao("Evolução", "O que é a especiação?", "Especiação é o processo pelo qual uma população de uma espécie se divide em duas ou mais novas espécies.");
criaCartao("Células", "O que são ribossomos?", "Ribossomos são organelas responsáveis pela síntese de proteínas nas células.");
criaCartao("Botânica", "O que são estômatos?", "Estômatos são pequenas aberturas nas folhas das plantas que permitem a troca de gases durante a fotossíntese.");
criaCartao("Ecologia", "O que é um ecossistema?", "Ecossistema é o conjunto de organismos vivos interagindo entre si e com o ambiente físico em uma área específica.");
criaCartao("Microbiologia", "O que é um vírus?", "Vírus são agentes infecciosos que não podem se reproduzir sozinhos e precisam invadir células hospedeiras para se replicar.");
criaCartao("Fisiologia", "O que é a circulação sanguínea?", "A circulação sanguínea é o movimento do sangue através dos vasos sanguíneos, transportando oxigênio e nutrientes.");
criaCartao("Genética", "O que são alelos?", "Alelos são diferentes formas de um gene que podem gerar variações nas características de um organismo.");
criaCartao("Botânica", "O que é a gametogênese?", "A gametogênese é o processo de formação dos gametas (óvulos e espermatozoides) nas células reprodutivas.");
criaCartao("Ecologia", "O que é o nicho ecológico?", "O nicho ecológico é o papel de uma espécie dentro de um ecossistema, incluindo suas interações com o ambiente.");
criaCartao("Fisiologia", "Qual a função do sistema respiratório?", "O sistema respiratório é responsável pela troca de gases, como oxigênio e dióxido de carbono, entre o organismo e o ambiente.");
criaCartao("Imunologia", "O que é uma infecção?", "Infecção é a invasão e multiplicação de microorganismos patogênicos no corpo, que podem causar doenças.");
criaCartao("Zoologia", "O que são anfíbios?", "Anfíbios são animais vertebrados que podem viver tanto na água quanto em ambientes terrestres.");
criaCartao("Biologia Molecular", "O que é a duplicação do DNA?", "A duplicação do DNA é o processo de replicação da molécula de DNA para garantir que cada célula filha tenha uma cópia.");
criaCartao("Fisiologia", "O que é a digestão?", "A digestão é o processo pelo qual o corpo quebra os alimentos em nutrientes absorvíveis, que são usados como energia e para o crescimento.");
criaCartao("Genética", "O que é a herança genética?", "A herança genética é o processo pelo qual características biológicas são transmitidas de uma geração para a outra através dos genes.");
